version: '3.8'
services:

  fibonacci:
    build: ./api/fibonacci
    ports:
      - 5050:5050
    volumes:
      - ./api/fibonacci:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  login:
    build: ./api/login
    ports:
      - 5051:5051
    volumes:
      - ./api/login:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  # logout:
  #   build: ./api/logout
  #   ports:
  #     - 5052:5052
  #   volumes:
  #     - ./api/logout:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  signup:
    build: ./api/signup
    ports:
      - 5053:5053
    volumes:
      - ./api/signup:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongodb

  # user:
  #   build: ./api/user
  #   ports:
  #     - 5054:5054
  #   volumes:
  #     - ./api/user:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
    # networks:
    #   - mern-app
    stdin_open: true
    tty: true
    depends_on:
      - fibonacci
      - login
      - logout
      - signup
      - user

  mongodb:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - data:/data/db

  nginx:
    depends_on:
      - fibonacci
      - login
      # - logout
      - signup
      # - user
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    build:
      dockerfile: dockerfile
      context: ./nginx
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  data: