FROM node:16.15.0

LABEL author="Ayush Singh"

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY . .

WORKDIR /app/src/db/session
RUN npm i

WORKDIR /app/src/db/user
RUN npm i

WORKDIR /app

EXPOSE 5051

CMD ["npm","run","dev"]